Add `Sendable` support & Add init function
Uhucream/SwiftyCIImageProperties pull request #8
Opened 2024-07-25 05:06 UTC by chocoford

2024-08-31 04:28 UTC, Uhucream commented
@chocoford 

Wow, thank you for your contribution!!!!

I'll check your this pull request.

2025-02-15 16:57 UTC, Uhucream requested changes
@chocoford 


Thank you for your contribution! 

I’ve pointed out some required changes and left a few questions in the comments. Could you take a look?

2025-02-15 16:57 UTC, Uhucream commented on .DS_Store
@chocoford 

[MUST]

Please delete it.

2025-02-15 16:57 UTC, Uhucream commented on Sources/.DS_Store
@chocoford 

[MUST]

Please delete it.

2025-02-15 16:57 UTC, Uhucream commented on Sources/SwiftyImageIO/.DS_Store
@chocoford 

[MUST]

Please delete it.

2025-02-15 16:57 UTC, Uhucream commented on SwiftyImageIO.playground/Contents.swift
@chocoford 

[IMO]

Thank you for making this change! However, since this is unrelated to the main topic of this PR, could you separate it into a different PR?

2025-02-15 16:57 UTC, Uhucream commented on SwiftyImageIO.playground/contents.xcplayground
@chocoford 

[IMO]

Thank you for making this change! However, since this is unrelated to the main topic of this PR, could you separate it into a different PR?

2025-02-15 16:57 UTC, Uhucream commented on Sources/SwiftyImageIO/CodableEntities/TIFF/TIFFProperty.swift
> +//}
@chocoford 

[MUST]

Please delete it which is unused dead code.

2025-02-15 16:57 UTC, Uhucream commented on Sources/SwiftyImageIO/CodableEntities/TIFF/TIFFProperty.swift
> +//            print("dateTimeString", dateTimeString)
@chocoford 

[MUST]

Please delete code for debug and it is unused.

2025-02-15 16:57 UTC, Uhucream commented on Sources/SwiftyImageIO/CodableEntities/Exif/ExifProperty.swift
> +    }
@chocoford 

[ASK]

Thank you for contributing to my project.

But I don't understand why did you add this?
I could not imagine use-case for this initializer because it is not public and I think this change deviates from the purpose of this GitHub project.

Could you explain the context where this would be needed?


[nits]

I think it should be declared on `extension` because "Memberwise Initializer" will be deleted if you write in struct declaration.

But at first, as mentioned, please explain purpose of this change.

2025-02-15 16:57 UTC, Uhucream commented on Sources/SwiftyImageIO/CodableEntities/GPS/GPSProperty.swift
> +    }
@chocoford 

[ASK]

Thank you for contributing to my project.

But I don't understand why did you add this?
I could not imagine use-case for this initializer because it is not public and I think this change deviates from the purpose of this GitHub project.

Could you explain the context where this would be needed?


[nits]

I think it should be declared on `extension` because "Memberwise Initializer" will be deleted if you write in struct declaration.

But at first, as mentioned, please explain purpose of this change.

2025-02-15 16:57 UTC, Uhucream commented on Sources/SwiftyImageIO/CodableEntities/MakerApple/MakerAppleProperty.swift
> +    }
@chocoford 

[ASK]

Thank you for contributing to my project.

But I don't understand why did you add this?
I could not imagine use-case for this initializer because it is not public and I think this change deviates from the purpose of this GitHub project.

Could you explain the context where this would be needed?


[nits]

I think it should be declared on `extension` because "Memberwise Initializer" will be deleted if you write in struct declaration.

But at first, as mentioned, please explain purpose of this change.

2025-02-15 16:57 UTC, Uhucream commented on Sources/SwiftyImageIO/CodableEntities/Properties/ImageIOProperties.swift
> +    }
@chocoford 

[ASK]

Thank you for contributing to my project.

But I don't understand why did you add this?
I could not imagine use-case for this initializer because it is not public and I think this change deviates from the purpose of this GitHub project.

Could you explain the context where this would be needed?


[nits]

I think it should be declared on `extension` because "Memberwise Initializer" will be deleted if you write in struct declaration.

But at first, as mentioned, please explain purpose of this change.@chocoford 

[ASK]

Thank you for contributing to my project.

But I don't understand why did you add this?
I could not imagine use-case for this initializer because I think this change deviates from the purpose of this GitHub project.

Could you explain the context where this would be needed?


[nits]

I think it should be declared on `extension` because "Memberwise Initializer" will be deleted if you write in struct declaration.

But at first, as mentioned, please explain purpose of this change.

2025-02-15 16:57 UTC, Uhucream commented on Sources/SwiftyImageIO/Extensions/Foundation/DateFormatter+.swift
> +        formatter.timeZone = TimeZone(secondsFromGMT: 0)
@chocoford 

[ASK]

Is this change compliant with the Exif specification?

https://exiftool.org/TagNames/EXIF.html#:~:text=(1%20or%202%20values%3A%201.%20the%20time%20zone%20offset%20of%20datetimeoriginal%20from%20gmt%20in%20hours%2C%202.%20if%20present%2C%20the%20time%20zone%20offset%20of%20modifydate)

2025-02-15 17:42 UTC, Uhucream commented on Sources/SwiftyImageIO/CodableEntities/MakerApple/MakerAppleProperty+CodingKeys.swift
> +        internal var rawValueInt: Int {
@chocoford 

[ASK]

Why did you make it internal?

And by the way, it can be omitted if it is `internal`.

2025-02-15 17:56 UTC, Uhucream commented on Sources/SwiftyImageIO/CodableEntities/MakerApple/MakerAppleProperty+RunTimeInformation.swift
>          }
@chocoford 

https://github.com/Uhucream/SwiftyImageIO/pull/8/files#diff-a0875ca30b22e199801b01915cf45de98429df9cfc301c0fc03fff4a7cb9cff7R15

I think it should be also changed

2025-02-22 05:47 UTC, chocoford commented on Sources/SwiftyImageIO/CodableEntities/Properties/ImageIOProperties.swift
> +    }
This is because we often need to retrieve image properties using `CGImageSourceCopyPropertiesAtIndex`. Therefore, an initializer based on `CFDictionary` is quite commonly used in this package.

2025-02-22 05:50 UTC, chocoford commented on Sources/SwiftyImageIO/CodableEntities/MakerApple/MakerAppleProperty+CodingKeys.swift
> +        internal var rawValueInt: Int {
This is because it is used in `MakerAppleProperty` init function.

2025-02-22 06:14 UTC, chocoford commented on Sources/SwiftyImageIO/CodableEntities/Properties/ImageIOProperties.swift
> +    }
> I think it should be declared on extension because "Memberwise Initializer" will be deleted if you write in struct declaration.

In fact, if an initializer is not explicitly defined, a public initializer will not be automatically generated for a class within the package.

2025-02-22 06:19 UTC, chocoford commented on Sources/SwiftyImageIO/Extensions/Foundation/DateFormatter+.swift
> +        formatter.timeZone = TimeZone(secondsFromGMT: 0)
Sorry, 🤥I cannot confirm this with certainty. This change was inferred based on the analysis of the EXIF information provided by Apple’s Gallery images.

2025-02-22 06:49 UTC, Uhucream commented on Sources/SwiftyImageIO/CodableEntities/Properties/ImageIOProperties.swift
> +    }
@chocoford 

> This is because we often need to retrieve image properties using CGImageSourceCopyPropertiesAtIndex. Therefore, an initializer based on CFDictionary is quite commonly used in this package.

No, that could not be the reason for this change.

I've updated README last week. See README to understand usage and main purpose for this package.

You will understand the reason that it is not needed to modify the dictionary after reading README.

No need to modify dictionary means no need to add init receiving dictionary I think.

2025-02-22 07:32 UTC, chocoford commented on Sources/SwiftyImageIO/CodableEntities/Properties/ImageIOProperties.swift
> +    }
@Uhucream 

Oh, sorry I didn't know the `ImageIOProperties` can be retrieved by `CIImage.swiftyImageProperties` before. 
Later I will delete the init functions added in this PR. 

And I will add a similar computed property for `CGImage`?

2025-02-22 07:35 UTC, Uhucream commented on Sources/SwiftyImageIO/Extensions/Foundation/DateFormatter+.swift
> +        formatter.timeZone = TimeZone(secondsFromGMT: 0)
OMG…

No problem!👍🏼

You must check whether it works or not with any other camera without iPhone.

2025-02-22 14:37 UTC, Uhucream commented on Sources/SwiftyImageIO/CodableEntities/Properties/ImageIOProperties.swift
> +    }
@chocoford 

> Oh, sorry I didn't know the ImageIOProperties can be retrieved by CIImage.swiftyImageProperties before.

No problem!
Because I didn’t write the README, it’s on me.

> Later I will delete the init functions added in this PR.

Yeah, thanks, go ahead!


> And I will add a similar computed property for CGImage?


No.
Because as you can see source codes, `swiftyImageProperties` is a Codable wrapper of `CIImage.properties`.
`CIImage.properties` is dictionary, and its result of dictionary is same as result of the function named `CGImageSourceCopyPropertiesAtIndex(_:, _:, _:)`.
But `CGImage` doesn't have any same instance property like `CIImage.properties`.

Thank you for suggestion, but I think that suggestion deviates from this library core concept that this library is just wrapper of `CIImage.properties`.

2025-02-22 15:02 UTC, Uhucream commented on Sources/SwiftyImageIO/CodableEntities/Properties/ImageIOProperties.swift
> +    }
@chocoford 

> And I will add a similar computed property for CGImage?


I appreciate your contributions to my library! It’s great to see your enthusiasm. As the next step, keeping PRs as small as possible and ensuring they stay focused on a single topic will make your contributions even more effective.

For example, this PR is focused on adding support for Swift Concurrency, so if you’d like to introduce additional changes, it would be best to submit them as separate PRs.

2025-02-22 15:03 UTC, Uhucream commented on Sources/SwiftyImageIO/Extensions/Foundation/DateFormatter+.swift
> +        formatter.timeZone = TimeZone(secondsFromGMT: 0)
But at first, this is unrelated change for corresponding Concurrency, so you should separate PR.

2025-02-22 15:07 UTC, Uhucream commented on Sources/SwiftyImageIO/Extensions/Foundation/DateFormatter+.swift
> +        formatter.locale = NSLocale.system //Locale(identifier: "en_US_POSIX")
@chocoford 

[ASK]

Why did you this comment?

2025-02-22 15:19 UTC, chocoford commented on Sources/SwiftyImageIO/Extensions/Foundation/DateFormatter+.swift
> +        formatter.timeZone = TimeZone(secondsFromGMT: 0)
OK I will remove this change in this PR.

2025-02-22 15:20 UTC, Uhucream commented
@chocoford 

You may run it instead of deleting these init and committing.

```bash
git reset --hard d4c1b96
git revert 9af113a61d855a972a1e39af14bb4e9197563805
git push -f origin HEAD
```

2025-02-22 15:23 UTC, Uhucream commented
@chocoford 

And you should create other PRs soon if you want to add changes

2025-02-22 15:28 UTC, Uhucream commented on Sources/SwiftyImageIO/CodableEntities/Exif/ExifProperty.swift
> +    public var isoSpeedRatings: [Int]?
@chocoford 

[MUST]

It is unrelated change for concurrency so you must seperate PR.

You can title it as "Fix typing mistakes".

2025-02-22 15:45 UTC, Uhucream commented on Sources/SwiftyImageIO/CodableEntities/MakerApple/MakerAppleProperty.swift
> +    }
@chocoford 

[MUST]

You can't mark this conversation as resolved because you don't delete this change.

2025-02-22 15:45 UTC, chocoford commented
OK I will revert all the relative changes later and keep the commits clean :D

2025-02-22 15:45 UTC, Uhucream commented on Sources/SwiftyImageIO/CodableEntities/Exif/ExifProperty.swift
> +    }
@chocoford 

[MUST]

You can't mark this conversation as resolved because you don't delete this change.

2025-02-26 03:23 UTC, chocoford commented
@Uhucream 
Is this good enough? If the commit is still too redundant, I'll submit a new PR.

2025-02-26 03:31 UTC, Uhucream commented
@chocoford 

> @Uhucream 
> 
> Is this good enough? If the commit is still too redundant, I'll submit a new PR.

Yes, it becomes clean now😆
Thank you for your cooperation!

2025-02-26 03:33 UTC, Uhucream approved these changes
@chocoford 

Thank you for contributing my library!

I apologize for some trouble for PR commits, but it was so good for your enthusiasm so I would like you to continue to contribute my project!

2025-02-26 03:33 UTC, merged